# -*- Mode: Python -*-

Import('env')

myenv = env.Clone()
#myenv.Append(CXXFLAGS = ' -finstrument-functions -DPROFILE')

crt0 = myenv.Object('crt0.o', 'arch/' + myenv['ARCH'] + '/crt0.S')
crt1 = myenv.Object('crt1.o', 'arch/' + myenv['ARCH'] + '/crt1.s')
crtn = myenv.Object('crtn.o', 'arch/' + myenv['ARCH'] + '/crtn.s')
myenv.Install(myenv['SYSGCCLIBPATH'], [crt0, crt1, crtn])

ccsrc = [Glob('*.cc'), Glob('*/*.cc'), Glob('*/' + myenv['ARCH'] + '/*.cc')]
csrc = [Glob('*.c'), Glob('*/*.c'), Glob('*/' + myenv['ARCH'] + '/*.c')]
ssrc = [Glob('arch/*.s'), Glob('*/' + myenv['ARCH'] + '/*.s')]
lib = myenv.StaticLibrary('libstdc++', ccsrc + csrc + ssrc)
myenv.Install(myenv['LIBPATH'], lib)
