# -*- Mode: Python -*-

Import('guestenv')

myenv = guestenv.Clone()
myenv['LINKFLAGS'] += ' -Wl,-T,guests/test/linker.ld'
prog = myenv.Program('guest_test', Glob('*.s'))
myenv.Install(myenv['BINARYDIR'], prog)
